In [1]:
#Importing Numpy Module
import numpy as np

In [2]:
fruit_list=["apple","banana","orange","pine apple"]

In [3]:
fruit_list=np.array(fruit_list)
print(fruit_list)

['apple' 'banana' 'orange' 'pine apple']


In [6]:
print(list(np.arange(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
years=np.arange( 1995, 2018, 1)
years

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017])

In [11]:
years.dtype

dtype('int64')

In [10]:
years.argmax()

22

In [13]:
years.argmin()

0

In [14]:
years.shape

(23,)

In [15]:
years.sum()

46138

In [16]:
years.size

23

In [18]:
years.min()

1995

In [20]:
years.max()

2017

In [22]:
years.mean().astype("int")

2006

In [25]:
fruit_list.astype("str").dtype

dtype('<U10')

In [24]:
fruit_list.dtype

dtype('<U10')

In [26]:
years.cumsum()

array([ 1995,  3991,  5988,  7986,  9985, 11985, 13986, 15988, 17991,
       19995, 22000, 24006, 26013, 28021, 30030, 32040, 34051, 36063,
       38076, 40090, 42105, 44121, 46138])

In [29]:
years.repeat(2)

array([1995, 1995, 1996, 1996, 1997, 1997, 1998, 1998, 1999, 1999, 2000,
       2000, 2001, 2001, 2002, 2002, 2003, 2003, 2004, 2004, 2005, 2005,
       2006, 2006, 2007, 2007, 2008, 2008, 2009, 2009, 2010, 2010, 2011,
       2011, 2012, 2012, 2013, 2013, 2014, 2014, 2015, 2015, 2016, 2016,
       2017, 2017])

In [9]:
a=np.array([2,10,5,6,7])
b=np.array([1,2,5,4,2])

In [33]:
a.dot(b)

85

In [34]:
print(type(a))

<class 'numpy.ndarray'>


In [37]:
c=np.array([a,b])
print(c)

[[ 2 10  5  6  7]
 [ 1  2  5  4  2]]


In [10]:
ab_dot_product = np.dot(a,b)
ab_dot_product

85

In [38]:
c.shape

(2, 5)

In [41]:
c_transpose=c.T
c_transpose

array([[ 2,  1],
       [10,  2],
       [ 5,  5],
       [ 6,  4],
       [ 7,  2]])

In [42]:
c_transpose.shape

(5, 2)

In [49]:
c[0,0:4]

array([ 2, 10,  5,  6])

In [52]:
#Identity Function

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
identity_matrix.diagonal()

array([1., 1., 1.])

In [56]:
c.diagonal()

array([2, 2])

In [59]:
#Random Matrix

random_matrix= np.random.random((4,5))  
print(random_matrix)


[[0.70567636 0.50429149 0.59421655 0.91910504 0.70005483]
 [0.91506596 0.12658469 0.32330811 0.0668446  0.73421065]
 [0.37242895 0.53631787 0.26565305 0.00097023 0.30672012]
 [0.22781962 0.63193691 0.86663534 0.02358567 0.74825727]]


In [60]:
np.sqrt(random_matrix)

array([[0.84004545, 0.71013484, 0.77085443, 0.95869966, 0.83669279],
       [0.9565908 , 0.35578742, 0.56860189, 0.25854323, 0.85686093],
       [0.61026957, 0.73233727, 0.51541541, 0.03114854, 0.55382318],
       [0.47730453, 0.79494459, 0.93093251, 0.15357628, 0.86501865]])

In [63]:
np.square(random_matrix)

array([[4.97979122e-01, 2.54309910e-01, 3.53093314e-01, 8.44754080e-01,
        4.90076765e-01],
       [8.37345706e-01, 1.60236829e-02, 1.04528136e-01, 4.46820051e-03,
        5.39065281e-01],
       [1.38703321e-01, 2.87636859e-01, 7.05715405e-02, 9.41349329e-07,
        9.40772316e-02],
       [5.19017788e-02, 3.99344255e-01, 7.51056808e-01, 5.56284054e-04,
        5.59888942e-01]])

In [64]:
random_matrix_2=np.random.random((4,5))

In [65]:
np.add(random_matrix,random_matrix_2)

array([[0.80157766, 0.65502167, 0.69852464, 1.73014243, 1.08826639],
       [1.39288248, 0.95936457, 1.28310394, 0.65763153, 0.7597128 ],
       [0.96387807, 0.92601998, 0.53551309, 0.92500724, 0.40698829],
       [1.08008311, 1.51397613, 1.32019435, 0.27862897, 1.24201127]])

In [66]:
np.subtract(random_matrix,random_matrix_2)

array([[ 0.60977505,  0.35356132,  0.48990847,  0.10806766,  0.31184327],
       [ 0.43724944, -0.70619519, -0.63648771, -0.52394233,  0.70870851],
       [-0.21902017,  0.14661576, -0.004207  , -0.92306678,  0.20645195],
       [-0.62444387, -0.25010231,  0.41307633, -0.23145762,  0.25450327]])

In [69]:
np.multiply(random_matrix,random_matrix_2)

array([[0.06767528, 0.07601195, 0.06198159, 0.74542855, 0.27176938],
       [0.43723363, 0.10541718, 0.31030978, 0.03949092, 0.01872395],
       [0.22027277, 0.20900421, 0.07168914, 0.00089653, 0.03075426],
       [0.19416234, 0.55739314, 0.39307026, 0.00601537, 0.36945502]])

In [75]:
np.divide(random_matrix,random_matrix_2)

array([[7.35836029e+00, 3.34565712e+00, 5.69674486e+00, 1.13324621e+00,
        1.80328177e+00],
       [1.91509904e+00, 1.52002575e-01, 3.36850927e-01, 1.13145022e-01,
        2.87901543e+01],
       [6.29688901e-01, 1.37622522e+00, 9.84410425e-01, 1.04999212e-03,
        3.05899795e+00],
       [2.67311250e-01, 7.16449898e-01, 1.91074440e+00, 9.24771427e-02,
        1.51544548e+00]])

In [76]:
np.sum(random_matrix,axis=0)

array([2.22099088, 1.79913096, 2.04981305, 1.01050555, 2.48924287])

In [77]:
np.sum(random_matrix,axis=1)

array([3.42334428, 2.16601401, 1.48209022, 2.49823481])

## String Operations

In [34]:
np.char.capitalize(["abc","bcd","cef"])

array(['Abc', 'Bcd', 'Cef'], dtype='<U3')

In [35]:
np.char.upper(["abc","bcd","cef"])

array(['ABC', 'BCD', 'CEF'], dtype='<U3')

In [16]:
np.char.add(['hello'],['world python']) 

array(['helloworld python'], dtype='<U17')

In [30]:
aa= np.char.center('hello world', 30,fillchar = '-')
aa

array('---------hello world----------', dtype='<U30')

In [31]:
np.char.split ("What is this function about?", sep = ' ')

array(list(['What', 'is', 'this', 'function', 'about?']), dtype=object)

In [5]:
np.char.strip(['arora','admin','javaded'],'d')

array(['arora', 'admin', 'javade'], dtype='<U7')

In [40]:
np.char.join('_',['abc','edf']) 

array(['a_b_c', 'e_d_f'], dtype='<U5')

In [2]:
import numpy as np

In [16]:
np.random.seed(10)
np.random.random((4,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578]])